-keep public class com.yubico.yubikit.fido.android.FidoWebViewSupportKt { *; }
-keep public class com.yubico.yubikit.fido.android.Origin { *; }
-keep public class com.yubico.yubikit.fido.android.FidoConfigManager { *; }
-keep public class com.yubico.yubikit.fido.android.FidoConfig { *; }
