== FIDO module

The FIDO module enables applications to authenticate WebAuthn credentials on a YubiKey.

The current implementation follows the https://www.w3.org/TR/webauthn-3/[Webauthn Level 3] and https://fidoalliance.org/specs/fido-v2.2-ps-20250714/fido-client-to-authenticator-protocol-v2.2-ps-20250714.html[CTAP 2.2] specifications and can include more properties from newer standard versions.

https://developers.yubico.com/yubikit-android/JavaDoc/fido/latest/[JavaDoc API documentation]

=== Dependency

To add the Fido module, along with the link:../android/[Android] module as a dependencies to your project, add the following to your gradle configuration:

[source,groovy]
----
dependencies {
  implementation 'com.yubico.yubikit:android:(insert version here)'
  implementation 'com.yubico.yubikit:fido:(insert version here)'
}
----

This module depends on the link:../core/[core] module, which will automatically be added as a transitive dependency to your project.

==== Communication with the FIDO Application

To communicate with the Fido application on a YubiKey, use the CtapSession class.
The class provides constructors for Fido or SmartCard connections, as well as a factory method which takes a YubiKeyDevice and will use the best suited connection type available.

The SDK provides a WebAuthn client implementation which communicates with the YubiKey through CTAP1 and CTAP2 and can make new credentials or assert existing credentials.
The client has also functionality for working with the PIN.

Credential operations provided by WebAuthnClient use classes which map to standard Webauthn types and allow easier interoperability with RPs.
For example `PublicKeyCredential.toMap()` returns a standard Java `Map` object which can be serialized to JSON representation:

[source,java]
----
CtapSession session = ...;
WebAuthnClient client = new WebAuthnClient(session);
PublicKeyCredential credential = client.makeCredential(params);
String response = JSONObject(credential.toMap()).toString();
----

