name: Android CI

on: [ push ]

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify code format
        run: ./gradlew spotlessCheck

      - name: Build with Gradle
        run: NO_GPG_SIGN=true ./gradlew --stacktrace check test javadocJar publishToMavenLocal

      - name: Upload jars
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: maven-repo
          path: ~/.m2/repository/com/yubico/yubikit/
