== Instrumented tests for YubiKit Android

This module contains tests for execution on a physical device and with YubiKey connected via USB or NFC. The test runs need a presence of someone who can tap the key when needed and therefore are these tests suitable only for local execution.

=== Recommended setup
1. A physical Android device running API 19+
2. YubiKey
3. (optional) OTG cable for connecting a YubiKey
** modern devices with USB-C connector will work with USB-C YubiKeys directly
** it is possible to run the tests over NFC as well, but it is much more convenient to use USB connection
4. Wireless debugging setup (see instructions in https://developer.android.com/studio/command-line/adb[official adb documentation]).
5. Recent version of Android Studio (Chipmunk and newer)

=== Managing YubiKeys for Testing
To protect your YubiKeys from accidental data changes during testing, you must specify which devices the test suite is allowed to use. This is done by creating a local allow list file containing the serial numbers of your designated test YubiKeys.

==== Instructions
1. Find the Serial Number: +
Connect your YubiKey and use the YubiKey Manager tool to find its serial number
2. Create the Allow List File: +
Create a new file at the following specific path in the project: +
`testing-android/src/main/assets/allowed_serials.csv`

3. Add Serial Numbers: +
Open `allowed_serials.csv` and add the serial numbers of your test YubiKeys. +
Separate each serial number with a comma or end of line. Do not add spaces or other text.
+
Example `allowed_serials.csv` content:
+
[literal]
----
1234567,9876543,1357911
1212121
2211545
----

The test framework will now only run on the YubiKeys specified in this file.

=== Running the tests
1. Make sure that the YubiKey you are using is meant for testing. Don't proceed with the tests if unsure.
 Running the instrumented tests will: change PIN, PUK, management key and overwrite stored certificates in the PIV application
2. Open `yubikit-android` project in Android Studio
3. Connect your device through wireless debugging and select it
4. Right-click the `testing-android` project and select _Run 'All tests'_

==== Running from commandline
It is also possible to run the tests from commandline by executing following command after the device is connected through adb:

  ./gradlew testing-android:connectedAndroidTest